// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC3CL8T7lw89fUDsdOmB_5kKiTTK8u2Zdg',
//     appId: '1:1067729404325:web:5bb161054e179473d1684c',
//     messagingSenderId: '1067729404325',
//     projectId: 'binhanpharmacy-810e4',
//     authDomain: 'binhanpharmacy-810e4.firebaseapp.com',
//     storageBucket: 'binhanpharmacy-810e4.firebasestorage.app',
//     measurementId: 'G-Q3HK4G81DE',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAqNsmtcxCix4yWVQb8bWH29SeK6Rt0t-I',
//     appId: '1:1067729404325:android:4f4c002ca6d11533d1684c',
//     messagingSenderId: '1067729404325',
//     projectId: 'binhanpharmacy-810e4',
//     storageBucket: 'binhanpharmacy-810e4.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDX0nE_PvkjTnvQQBcbV6U7EVoaQMvt7so',
//     appId: '1:1067729404325:ios:83247259e783b89fd1684c',
//     messagingSenderId: '1067729404325',
//     projectId: 'binhanpharmacy-810e4',
//     storageBucket: 'binhanpharmacy-810e4.firebasestorage.app',
//     iosBundleId: 'vn.edu.iuh.fit.binhAnPharmacy',
//   );
// }
